# Generated by Django 4.1.7 on 2023-04-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire_talents', '0009_clientdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetail',
            old_name='detail',
            new_name='detail_id',
        ),
    ]
