# Generated by Django 4.1.7 on 2023-04-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_talents', '0011_alter_clientdetail_detail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='meeting_done',
            field=models.BooleanField(default=False),
        ),
    ]
