# Generated by Django 4.1.7 on 2023-03-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire_talents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
