# Generated by Django 4.1.7 on 2023-03-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire_talents', '0002_rename_options_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire_talents.user')),
            ],
        ),
    ]
