# Generated by Django 4.1.7 on 2023-03-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire_talents', '0003_userrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequirement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRequirement',
        ),
    ]
