# Generated by Django 4.1.7 on 2023-03-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djf_surveys', '0011_alter_question_key'),
        ('hire_talents', '0004_remove_userrequirement_user_delete_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_image', models.ImageField(upload_to='images/')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djf_surveys.answer')),
            ],
        ),
    ]
