# Generated by Django 4.1.7 on 2023-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_talents', '0008_alter_developerimage_answer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_ids', models.CharField(max_length=300)),
                ('detail', models.IntegerField()),
            ],
        ),
    ]
