# Generated by Django 4.1.7 on 2023-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_talents', '0012_clientdetail_meeting_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='detail_id',
            field=models.IntegerField(),
        ),
    ]
